services:

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: courseadmin
      POSTGRES_PASSWORD: opencourse149521
      POSTGRES_DB: opencoursecrm

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080