spring:
  application:
    name: CG-Courses-CRM
  datasource:
    driver-class-name: org.postgresql.Driver
    username: courseadmin
    # Use DATABASE_PASSWORD env variable or fallback to default value
    # ${ENV_VAR:FALLBACK_DEFAULT_VALUE}
    password: ${DATABASE_PASSWORD:opencourse149521}
    url: jdbc:postgresql://localhost:5432/opencoursecrm

