spring:
  application:
    name: CG-Courses-CRM
  datasource:
    driver-class-name: org.postgresql.Driver
    username: courseadmin
    password: ${DATABASE_PASSWORD}
    url: jdbc:postgresql://localhost:5432/opencoursecrm